http://localhost:4000/api/auth/test

###

post http://localhost:4000/api/auth/register
Content-Type: application/json


{
    "username" : "test",
    "email" : "test@gmail.com",
    "password" : "12345678"
}

###

post http://localhost:4000/api/auth/login
Content-Type: application/json


{
    "email" : "ajmal@gmail.com",
    "password" : "12345678" 
}


###


get http://localhost:4000/api/auth/test
Authorization: Bearer 111111111111111111111111111
Content-Type: application/json
